services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: YOUR_LARAVEL_APP_KEY
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://your-laravel-app.onrender.com
